toggleClass('menu-btn', 'toggle-menu')

closeClass('menu-overview', 'toggle-menu')
closeClass('menu-prereqs', 'toggle-menu')
closeClass('menu-plan', 'toggle-menu')
closeClass('menu-area', 'toggle-menu')
closeClass('menu-cell', 'toggle-menu')
closeClass('menu-rules', 'toggle-menu')
closeClass('menu-game', 'toggle-menu')
closeClass('menu-loop', 'toggle-menu')
// closeClass('menu-metrics', 'toggle-menu')
// closeClass('menu-controls', 'toggle-menu')
closeClass('menu-code', 'toggle-menu')

closeClass('intro', 'toggle-menu')
closeClass('overview', 'toggle-menu')
closeClass('prereqs', 'toggle-menu')
closeClass('plan', 'toggle-menu')
closeClass('area', 'toggle-menu')
closeClass('cell', 'toggle-menu')
closeClass('rules', 'toggle-menu')
closeClass('game', 'toggle-menu')
closeClass('loop', 'toggle-menu')
// closeClass('metrics', 'toggle-menu')
// closeClass('controls', 'toggle-menu')
closeClass('code', 'toggle-menu')
closeClass('bottom-spacer', 'toggle-menu')
